# Generated by Django 2.0.6 on 2018-07-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now=True)),
                ('run_duration', models.IntegerField(max_length=64)),
                ('on_schedule', models.BooleanField()),
                ('as_delay', models.BooleanField()),
                ('delay_reason', models.CharField(choices=[('W', 'Weather'), ('M', 'Manual')], default='W', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.IntegerField(max_length=64, unique=True)),
                ('pin_number', models.IntegerField(max_length=64)),
                ('zone_name', models.CharField(blank=True, max_length=64, null=True)),
                ('run_duration', models.IntegerField(default=900, max_length=64)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('alternate_days', models.BooleanField(default=False)),
                ('run_next', models.BooleanField(default=False)),
                ('postponed', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='zone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controler.Zone', to_field='zone_number'),
        ),
    ]
